defaults: &defaults
 
:development:
  :couchdb:
    :url: http://localhost:5984/thechallenge_development
  <<: *defaults
  
:test:
  :couchdb:
    :url: http://localhost:5984/thechallenge_test
    <<: *defaults

:production:
  :couchdb:
    :url: http://localhost:5984/thechallenge_production
    <<: *defaults